package com.demo.model;

import java.util.Date;

public class Appointment extends AppointmentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment
     *
     * @mbg.generated Wed Dec 05 23:21:39 CST 2018
     */
    private Date appointment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment
     *
     * @return the value of appointment.appointment
     *
     * @mbg.generated Wed Dec 05 23:21:39 CST 2018
     */
    public Date getAppointment() {
        return appointment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment
     *
     * @param appointment the value for appointment.appointment
     *
     * @mbg.generated Wed Dec 05 23:21:39 CST 2018
     */
    public void setAppointment(Date appointment) {
        this.appointment = appointment;
    }
}